/**
 * Enumerates the structured audit event types emitted by the engine.
 *
 * Audit events form an immutable ledger of every material state transition,
 * which is essential for debugging durable execution and for driving alerts.
 */
export enum EventType {
  WORKFLOW_STARTED = "WORKFLOW_STARTED",
  WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED",
  WORKFLOW_FAILED = "WORKFLOW_FAILED",
  WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED",
  STEP_STARTED = "STEP_STARTED",
  STEP_COMPLETED = "STEP_COMPLETED",
  STEP_FAILED = "STEP_FAILED",
  STEP_RETRY_SCHEDULED = "STEP_RETRY_SCHEDULED",
  STEP_OPTIONAL_FAILED = "STEP_OPTIONAL_FAILED",
  STEP_AMBIGUOUS = "STEP_AMBIGUOUS",
  STEP_PROBE_STARTED = "STEP_PROBE_STARTED",
  STEP_PROBE_RESOLVED = "STEP_PROBE_RESOLVED",
  STEP_PROBE_EMPTY = "STEP_PROBE_EMPTY",
  STEP_NEEDS_REVIEW = "STEP_NEEDS_REVIEW",
  TIMER_SCHEDULED = "TIMER_SCHEDULED",
  CIRCUIT_OPEN = "CIRCUIT_OPEN",
  CIRCUIT_CLOSED = "CIRCUIT_CLOSED",
  CIRCUIT_HALF_OPEN = "CIRCUIT_HALF_OPEN",
  ALERT_SENT = "ALERT_SENT",
}
